version: '3.3'

services:
  bot:
    build: .
    image: ${APP_IMAGE_NAME}
    command: ["/app/docker/bot.sh"]
    volumes:
      - .env:/app/.env
    networks:
      - main
    depends_on:
      - db
      - redis

  tgbot:
    build: .
    image: ${APP_IMAGE_NAME}
    command: ["/app/docker/bot.sh", "tgbot"]
    volumes:
      - .env:/app/.env
    networks:
      - main
    depends_on:
      - db

  tgbot-filtered:
    build: .
    image: ${APP_IMAGE_NAME}
    command: ["/app/docker/bot.sh", "tgbot-filtered"]
    volumes:
      - .env:/app/.env
    networks:
      - main
    depends_on:
      - db

  db:
    build: ./docker/postgres/.
    image: ${DB_IMAGE_NAME}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - main

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - main

  celery:
    build: .
    image: ${APP_IMAGE_NAME}
    command: ["/app/docker/celery.sh", "celery"]
    volumes:
      - ./.env:/app/.env:ro
      - ./service_account.json:/app/service_account.json:ro
    networks:
      - main
    depends_on:
      - db

  celery-beat:
    build: .
    image: ${APP_IMAGE_NAME}
    command: ["/app/docker/celery.sh", "beat"]
    volumes:
      - .env:/app/.env
    networks:
      - main
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  main:
    driver: bridge
