version: '3.3'

services:
  bot:
    build: .
    image: ${APP_IMAGE_NAME}
    restart: always
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 125m
    command: ["/app/docker/bot.sh"]
    networks:
      - main
    depends_on:
      - db

  db:
    build: ./docker/postgres/.
    image: ${DB_IMAGE_NAME}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 150m
    ports:
      - "5435:5432"
    networks:
      - main

  redis:
    image: redis:7
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50m
    ports:
      - "6380:6379"
    networks:
      - main

  celery:
    build: .
    image: ${APP_IMAGE_NAME}
    restart: always
    command: ["/app/docker/celery.sh", "celery"]
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 125m
    networks:
      - main
    depends_on:
      - db

  celery-beat:
    build: .
    image: ${APP_IMAGE_NAME}
    restart: always
    command: ["/app/docker/celery.sh", "beat"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 75m
    networks:
      - main
    depends_on:
      - redis
      - celery

  flower:
    build: .
    image: ${APP_IMAGE_NAME}
    environment:
      - FLOWER_UNAUTHENTICATED_API=True
    restart: always
    command: ["/app/docker/celery.sh", "flower"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50m
    ports:
      - "5555:5555"
    networks:
      - main
    depends_on:
      - redis
      - celery

networks:
  main:
    driver: overlay
