"""Add max liquid amount for specific exchange

Revision ID: 0fec0d5010ab
Revises: 7774d5fe6eb5
Create Date: 2024-03-12 23:43:25.056793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fec0d5010ab'
down_revision: Union[str, None] = '7774d5fe6eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_network_exchange', 'is_hidden')
    op.add_column('exchanges', sa.Column('max_liquid_amount', sa.Integer(), server_default='800', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'max_liquid_amount')
    op.add_column('coin_network_exchange', sa.Column('is_hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
