"""init

Revision ID: 731e0dd7832a
Revises: 
Create Date: 2023-12-13 11:40:42.152885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "731e0dd7832a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coins_created_at"), "coins", ["created_at"], unique=False)
    op.create_table(
        "exchanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exchanges_created_at"), "exchanges", ["created_at"], unique=False)
    op.create_table(
        "networks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_networks_created_at"), "networks", ["created_at"], unique=False)
    op.create_table(
        "coin_network_exchange",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("coin_id", sa.Integer(), nullable=True),
        sa.Column("network_id", sa.Integer(), nullable=True),
        sa.Column("arrival_time", sa.Integer(), nullable=True),
        sa.Column("withdraw_fee", sa.Float(), nullable=True),
        sa.Column("can_withdraw", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_deposit", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coin_id"],
            ["coins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["networks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coin_network_exchange_created_at"), "coin_network_exchange", ["created_at"], unique=False
    )
    op.create_table(
        "pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_coin_id", sa.Integer(), nullable=True),
        sa.Column("quote_coin_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_coin_id"],
            ["coins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_coin_id"],
            ["coins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pairs_created_at"), "pairs", ["created_at"], unique=False)
    op.create_table(
        "pair_exchanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=True),
        sa.Column("exchange_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pair_exchanges_created_at"), "pair_exchanges", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pair_exchanges_created_at"), table_name="pair_exchanges")
    op.drop_table("pair_exchanges")
    op.drop_index(op.f("ix_pairs_created_at"), table_name="pairs")
    op.drop_table("pairs")
    op.drop_index(op.f("ix_coin_network_exchange_created_at"), table_name="coin_network_exchange")
    op.drop_table("coin_network_exchange")
    op.drop_index(op.f("ix_networks_created_at"), table_name="networks")
    op.drop_table("networks")
    op.drop_index(op.f("ix_exchanges_created_at"), table_name="exchanges")
    op.drop_table("exchanges")
    op.drop_index(op.f("ix_coins_created_at"), table_name="coins")
    op.drop_table("coins")
    # ### end Alembic commands ###
