"""Add base network as part of networks mapping logic

Revision ID: b28ba98c76d2
Revises: ed1cdf5c44af
Create Date: 2024-01-28 00:40:18.441248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b28ba98c76d2"
down_revision: Union[str, None] = "ed1cdf5c44af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("coin_network_exchange", sa.Column("base_network_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_coin_network_exchange_base_network_id"), "coin_network_exchange", ["base_network_id"], unique=False
    )
    op.create_foreign_key(None, "coin_network_exchange", "networks", ["base_network_id"], ["id"])
    op.create_index(op.f("ix_networks_name"), "networks", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_networks_name"), table_name="networks")
    op.drop_constraint(None, "coin_network_exchange", type_="foreignkey")
    op.drop_index(op.f("ix_coin_network_exchange_base_network_id"), table_name="coin_network_exchange")
    op.drop_column("coin_network_exchange", "base_network_id")
    # ### end Alembic commands ###
