name: "CI/CD"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Run Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@23.12.1
        with:
          options: "-l 118 --check --diff --color"

  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push'
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_IMAGE_NAME: ${{ secrets.APP_IMAGE_NAME }}
      DB_IMAGE_NAME: ${{ secrets.DB_IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: "Login to Docker"
        run: |
          docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: "Build and push"
        run: |
          docker-compose build
          docker-compose push

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'push'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_JSON }}'
      - uses: google-github-actions/ssh-compute@v1.1.0
        with:
          instance_name: ${{ secrets.INSTANCE_NAME }}
          zone: ${{ secrets.INSTANCE_ZONE }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd bot
            git pull
            
            docker-compose up -d --pull always